apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple_helm.fullname" . }}
  {{- with .Values.serviceAnnotations }}
  annotations:
      {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "simple_helm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "simple_helm.selectorLabels" . | nindent 4 }}
